apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-api
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: n8n-api
      {{- include "n8n.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: n8n-api
        {{- include "n8n.labels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}

      containers:
        - name: n8n
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command: {{- toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.image.args }}
          args: {{- toYaml .Values.image.args | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 5678
          env:
            - name: N8N_PORT
              value: "5678"
            - name: N8N_HOST
              value: "0.0.0.0"
            {{- if .Values.ingress.enabled }}
            - name: N8N_PROTOCOL
              value: {{ .Values.ingress.protocol | default "http" | quote }}
            - name: WEBHOOK_URL
              value: "{{ .Values.ingress.protocol | default "http" }}://{{ .Values.ingress.host }}/"
            {{- end }}
            - name: GENERIC_TIMEZONE
              value: "{{ .Values.timezone }}"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: DB_TYPE
              value: sqlite
            - name: DB_SQLITE_VACUUM_ON_STARTUP
              value: "true"
          volumeMounts:
            - name: n8n-data
              mountPath: {{ .Values.persistence.mountPath }}

      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc


