apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: n8n-api
  template:
    metadata:
      labels:
        app: n8n-api
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: n8n
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5678
          env:
            - name: N8N_PORT
              value: "5678"
            - name: N8N_HOST
              value: "0.0.0.0"
            - name: GENERIC_TIMEZONE
              value: "{{ .Values.timezone }}"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: DB_TYPE
              value: sqlite
            - name: DB_SQLITE_VACUUM_ON_STARTUP
              value: "true"
          volumeMounts:
            - name: n8n-data
              mountPath: {{ .Values.persistence.mountPath }}

      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc


