apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-dev-api
spec:
  replicas: {{ .Values.pods.api.replicas }}
  selector:
    matchLabels:
      app: n8n-dev-api
  template:
    metadata:
      labels:
        app: n8n-dev-api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: api
          image: "{{ .Values.pods.api.containers.api.image.repository }}:{{ .Values.pods.api.containers.api.image.tag }}"
          ports:
            - containerPort: 5678
          env:
            {{- range .Values.pods.api.containers.api.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          volumeMounts:
            {{- range .Values.pods.api.containers.api.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
        {{- end }}
