version: "3.8"
services:
  n8n:
    build:
      context: ../docker
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Australia/Sydney
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n